// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: gameddz.proto

package gameddz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMDGameddz int32

const (
	CMDGameddz_IDGameStart   CMDGameddz = 1  //
	CMDGameddz_IDReSendCard  CMDGameddz = 2  //
	CMDGameddz_IDCallLandReq CMDGameddz = 3  //
	CMDGameddz_IDCallLandRsp CMDGameddz = 4  //
	CMDGameddz_IDConfirmLand CMDGameddz = 5  //
	CMDGameddz_IDOutCardReq  CMDGameddz = 6  //
	CMDGameddz_IDOutCardRsp  CMDGameddz = 7  //
	CMDGameddz_IDGameDataReq CMDGameddz = 8  //
	CMDGameddz_IDGameDataRsp CMDGameddz = 9  //
	CMDGameddz_IDGameOver    CMDGameddz = 10 //
)

// Enum value maps for CMDGameddz.
var (
	CMDGameddz_name = map[int32]string{
		1:  "IDGameStart",
		2:  "IDReSendCard",
		3:  "IDCallLandReq",
		4:  "IDCallLandRsp",
		5:  "IDConfirmLand",
		6:  "IDOutCardReq",
		7:  "IDOutCardRsp",
		8:  "IDGameDataReq",
		9:  "IDGameDataRsp",
		10: "IDGameOver",
	}
	CMDGameddz_value = map[string]int32{
		"IDGameStart":   1,
		"IDReSendCard":  2,
		"IDCallLandReq": 3,
		"IDCallLandRsp": 4,
		"IDConfirmLand": 5,
		"IDOutCardReq":  6,
		"IDOutCardRsp":  7,
		"IDGameDataReq": 8,
		"IDGameDataRsp": 9,
		"IDGameOver":    10,
	}
)

func (x CMDGameddz) Enum() *CMDGameddz {
	p := new(CMDGameddz)
	*p = x
	return p
}

func (x CMDGameddz) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMDGameddz) Descriptor() protoreflect.EnumDescriptor {
	return file_gameddz_proto_enumTypes[0].Descriptor()
}

func (CMDGameddz) Type() protoreflect.EnumType {
	return &file_gameddz_proto_enumTypes[0]
}

func (x CMDGameddz) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMDGameddz) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMDGameddz(num)
	return nil
}

// Deprecated: Use CMDGameddz.Descriptor instead.
func (CMDGameddz) EnumDescriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{0}
}

type GameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentSeat *uint32  `protobuf:"varint,1,opt,name=current_seat,json=currentSeat" json:"current_seat,omitempty"`
	HandCard    [][]byte `protobuf:"bytes,2,rep,name=hand_card,json=handCard" json:"hand_card,omitempty"`
	UserState   [][]byte `protobuf:"bytes,3,rep,name=user_state,json=userState" json:"user_state,omitempty"`
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{0}
}

func (x *GameStart) GetCurrentSeat() uint32 {
	if x != nil && x.CurrentSeat != nil {
		return *x.CurrentSeat
	}
	return 0
}

func (x *GameStart) GetHandCard() [][]byte {
	if x != nil {
		return x.HandCard
	}
	return nil
}

func (x *GameStart) GetUserState() [][]byte {
	if x != nil {
		return x.UserState
	}
	return nil
}

type ReSendCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentSeat *uint32  `protobuf:"varint,1,opt,name=current_seat,json=currentSeat" json:"current_seat,omitempty"`
	HandCard    [][]byte `protobuf:"bytes,2,rep,name=hand_card,json=handCard" json:"hand_card,omitempty"`
}

func (x *ReSendCard) Reset() {
	*x = ReSendCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReSendCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReSendCard) ProtoMessage() {}

func (x *ReSendCard) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReSendCard.ProtoReflect.Descriptor instead.
func (*ReSendCard) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{1}
}

func (x *ReSendCard) GetCurrentSeat() uint32 {
	if x != nil && x.CurrentSeat != nil {
		return *x.CurrentSeat
	}
	return 0
}

func (x *ReSendCard) GetHandCard() [][]byte {
	if x != nil {
		return x.HandCard
	}
	return nil
}

type CallLandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallScore *uint32 `protobuf:"varint,1,opt,name=call_score,json=callScore" json:"call_score,omitempty"`
}

func (x *CallLandReq) Reset() {
	*x = CallLandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallLandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallLandReq) ProtoMessage() {}

func (x *CallLandReq) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallLandReq.ProtoReflect.Descriptor instead.
func (*CallLandReq) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{2}
}

func (x *CallLandReq) GetCallScore() uint32 {
	if x != nil && x.CallScore != nil {
		return *x.CallScore
	}
	return 0
}

type CallLandRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentSeat *uint32  `protobuf:"varint,1,opt,name=current_seat,json=currentSeat" json:"current_seat,omitempty"`
	CallSeat    *uint32  `protobuf:"varint,2,opt,name=call_seat,json=callSeat" json:"call_seat,omitempty"`
	CallScore   *uint32  `protobuf:"varint,3,opt,name=call_score,json=callScore" json:"call_score,omitempty"`
	CurTimes    []uint32 `protobuf:"varint,4,rep,name=cur_times,json=curTimes" json:"cur_times,omitempty"`
}

func (x *CallLandRsp) Reset() {
	*x = CallLandRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallLandRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallLandRsp) ProtoMessage() {}

func (x *CallLandRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallLandRsp.ProtoReflect.Descriptor instead.
func (*CallLandRsp) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{3}
}

func (x *CallLandRsp) GetCurrentSeat() uint32 {
	if x != nil && x.CurrentSeat != nil {
		return *x.CurrentSeat
	}
	return 0
}

func (x *CallLandRsp) GetCallSeat() uint32 {
	if x != nil && x.CallSeat != nil {
		return *x.CallSeat
	}
	return 0
}

func (x *CallLandRsp) GetCallScore() uint32 {
	if x != nil && x.CallScore != nil {
		return *x.CallScore
	}
	return 0
}

func (x *CallLandRsp) GetCurTimes() []uint32 {
	if x != nil {
		return x.CurTimes
	}
	return nil
}

type ConfirmLand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentSeat *uint32  `protobuf:"varint,1,opt,name=current_seat,json=currentSeat" json:"current_seat,omitempty"`
	LandSeat    *uint32  `protobuf:"varint,2,opt,name=land_seat,json=landSeat" json:"land_seat,omitempty"`
	BottomCard  []byte   `protobuf:"bytes,3,opt,name=bottom_card,json=bottomCard" json:"bottom_card,omitempty"`
	CurTimes    []uint32 `protobuf:"varint,4,rep,name=cur_times,json=curTimes" json:"cur_times,omitempty"`
}

func (x *ConfirmLand) Reset() {
	*x = ConfirmLand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmLand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLand) ProtoMessage() {}

func (x *ConfirmLand) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLand.ProtoReflect.Descriptor instead.
func (*ConfirmLand) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmLand) GetCurrentSeat() uint32 {
	if x != nil && x.CurrentSeat != nil {
		return *x.CurrentSeat
	}
	return 0
}

func (x *ConfirmLand) GetLandSeat() uint32 {
	if x != nil && x.LandSeat != nil {
		return *x.LandSeat
	}
	return 0
}

func (x *ConfirmLand) GetBottomCard() []byte {
	if x != nil {
		return x.BottomCard
	}
	return nil
}

func (x *ConfirmLand) GetCurTimes() []uint32 {
	if x != nil {
		return x.CurTimes
	}
	return nil
}

type OutCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutCard []byte `protobuf:"bytes,1,opt,name=out_card,json=outCard" json:"out_card,omitempty"`
}

func (x *OutCardReq) Reset() {
	*x = OutCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutCardReq) ProtoMessage() {}

func (x *OutCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutCardReq.ProtoReflect.Descriptor instead.
func (*OutCardReq) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{5}
}

func (x *OutCardReq) GetOutCard() []byte {
	if x != nil {
		return x.OutCard
	}
	return nil
}

type OutCardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentSeat *uint32 `protobuf:"varint,1,opt,name=current_seat,json=currentSeat" json:"current_seat,omitempty"`
	OutcardSeat *uint32 `protobuf:"varint,2,opt,name=outcard_seat,json=outcardSeat" json:"outcard_seat,omitempty"`
	OutCard     []byte  `protobuf:"bytes,3,opt,name=out_card,json=outCard" json:"out_card,omitempty"`
}

func (x *OutCardRsp) Reset() {
	*x = OutCardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutCardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutCardRsp) ProtoMessage() {}

func (x *OutCardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutCardRsp.ProtoReflect.Descriptor instead.
func (*OutCardRsp) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{6}
}

func (x *OutCardRsp) GetCurrentSeat() uint32 {
	if x != nil && x.CurrentSeat != nil {
		return *x.CurrentSeat
	}
	return 0
}

func (x *OutCardRsp) GetOutcardSeat() uint32 {
	if x != nil && x.OutcardSeat != nil {
		return *x.OutcardSeat
	}
	return 0
}

func (x *OutCardRsp) GetOutCard() []byte {
	if x != nil {
		return x.OutCard
	}
	return nil
}

type UserState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserState) Reset() {
	*x = UserState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserState) ProtoMessage() {}

func (x *UserState) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserState.ProtoReflect.Descriptor instead.
func (*UserState) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{7}
}

type GameDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameDataReq) Reset() {
	*x = GameDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDataReq) ProtoMessage() {}

func (x *GameDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDataReq.ProtoReflect.Descriptor instead.
func (*GameDataReq) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{8}
}

type GameDataRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameDataRsp) Reset() {
	*x = GameDataRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDataRsp) ProtoMessage() {}

func (x *GameDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDataRsp.ProtoReflect.Descriptor instead.
func (*GameDataRsp) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{9}
}

type GameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinSeat *uint32 `protobuf:"varint,1,opt,name=win_seat,json=winSeat" json:"win_seat,omitempty"`
	Score   []int64 `protobuf:"varint,2,rep,name=score" json:"score,omitempty"`
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameddz_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_gameddz_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_gameddz_proto_rawDescGZIP(), []int{10}
}

func (x *GameOver) GetWinSeat() uint32 {
	if x != nil && x.WinSeat != nil {
		return *x.WinSeat
	}
	return 0
}

func (x *GameOver) GetScore() []int64 {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_gameddz_proto protoreflect.FileDescriptor

var file_gameddz_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x64, 0x64, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x62, 0x73, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x64, 0x64, 0x7a, 0x22, 0x6a, 0x0a, 0x09, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68,
	0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08,
	0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4c, 0x0a, 0x0a, 0x52, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64,
	0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x68, 0x61, 0x6e,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x22, 0x2c, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x4c, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x4c, 0x61, 0x6e, 0x64,
	0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x73,
	0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x53,
	0x65, 0x61, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22,
	0x8b, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4c, 0x61, 0x6e, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x61, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x27, 0x0a,
	0x0a, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x6f,
	0x75, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6f,
	0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x6d, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6f,
	0x75, 0x74, 0x63, 0x61, 0x72, 0x64, 0x53, 0x65, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x75,
	0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6f, 0x75,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70,
	0x22, 0x3b, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x77, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x77, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0xc2, 0x01,
	0x0a, 0x0a, 0x43, 0x4d, 0x44, 0x47, 0x61, 0x6d, 0x65, 0x64, 0x64, 0x7a, 0x12, 0x0f, 0x0a, 0x0b,
	0x49, 0x44, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x49, 0x44, 0x52, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x10, 0x02, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x44, 0x43, 0x61, 0x6c, 0x6c, 0x4c, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x44, 0x43, 0x61, 0x6c, 0x6c, 0x4c, 0x61, 0x6e, 0x64,
	0x52, 0x73, 0x70, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x44, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x4c, 0x61, 0x6e, 0x64, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x44, 0x4f, 0x75,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x44,
	0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x73, 0x70, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d,
	0x49, 0x44, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x10, 0x08, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x44, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70,
	0x10, 0x09, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x44, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72,
	0x10, 0x0a, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x64, 0x64, 0x7a,
}

var (
	file_gameddz_proto_rawDescOnce sync.Once
	file_gameddz_proto_rawDescData = file_gameddz_proto_rawDesc
)

func file_gameddz_proto_rawDescGZIP() []byte {
	file_gameddz_proto_rawDescOnce.Do(func() {
		file_gameddz_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameddz_proto_rawDescData)
	})
	return file_gameddz_proto_rawDescData
}

var file_gameddz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gameddz_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gameddz_proto_goTypes = []interface{}{
	(CMDGameddz)(0),     // 0: bs.gameddz.CMDGameddz
	(*GameStart)(nil),   // 1: bs.gameddz.GameStart
	(*ReSendCard)(nil),  // 2: bs.gameddz.ReSendCard
	(*CallLandReq)(nil), // 3: bs.gameddz.CallLandReq
	(*CallLandRsp)(nil), // 4: bs.gameddz.CallLandRsp
	(*ConfirmLand)(nil), // 5: bs.gameddz.ConfirmLand
	(*OutCardReq)(nil),  // 6: bs.gameddz.OutCardReq
	(*OutCardRsp)(nil),  // 7: bs.gameddz.OutCardRsp
	(*UserState)(nil),   // 8: bs.gameddz.UserState
	(*GameDataReq)(nil), // 9: bs.gameddz.GameDataReq
	(*GameDataRsp)(nil), // 10: bs.gameddz.GameDataRsp
	(*GameOver)(nil),    // 11: bs.gameddz.GameOver
}
var file_gameddz_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameddz_proto_init() }
func file_gameddz_proto_init() {
	if File_gameddz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gameddz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReSendCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallLandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallLandRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmLand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutCardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDataRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameddz_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameddz_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gameddz_proto_goTypes,
		DependencyIndexes: file_gameddz_proto_depIdxs,
		EnumInfos:         file_gameddz_proto_enumTypes,
		MessageInfos:      file_gameddz_proto_msgTypes,
	}.Build()
	File_gameddz_proto = out.File
	file_gameddz_proto_rawDesc = nil
	file_gameddz_proto_goTypes = nil
	file_gameddz_proto_depIdxs = nil
}
