// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMDConfig int32

const (
	CMDConfig_IDConfigReq    CMDConfig = 1 // 请求配置
	CMDConfig_IDConfigRsp    CMDConfig = 2 // 配置响应
	CMDConfig_IDItemRspState CMDConfig = 3 // 配置响应状态
)

// Enum value maps for CMDConfig.
var (
	CMDConfig_name = map[int32]string{
		1: "IDConfigReq",
		2: "IDConfigRsp",
		3: "IDItemRspState",
	}
	CMDConfig_value = map[string]int32{
		"IDConfigReq":    1,
		"IDConfigRsp":    2,
		"IDItemRspState": 3,
	}
)

func (x CMDConfig) Enum() *CMDConfig {
	p := new(CMDConfig)
	*p = x
	return p
}

func (x CMDConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMDConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (CMDConfig) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x CMDConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMDConfig) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMDConfig(num)
	return nil
}

// Deprecated: Use CMDConfig.Descriptor instead.
func (CMDConfig) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type ConfigReq_EnumSubscribe int32

const (
	ConfigReq_NOT_SUBSCRIBE ConfigReq_EnumSubscribe = 0 // 不订阅
	ConfigReq_SUBSCRIBE     ConfigReq_EnumSubscribe = 1 // 订阅，成功就下发配置
	ConfigReq_UNSUBSCRIBE   ConfigReq_EnumSubscribe = 2 // 取消订阅
	ConfigReq_NEED_RSP      ConfigReq_EnumSubscribe = 4 // 要求回复，下发配置
	ConfigReq_NO_RSP        ConfigReq_EnumSubscribe = 8 // 不要回复，不下发配置
)

// Enum value maps for ConfigReq_EnumSubscribe.
var (
	ConfigReq_EnumSubscribe_name = map[int32]string{
		0: "NOT_SUBSCRIBE",
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
		4: "NEED_RSP",
		8: "NO_RSP",
	}
	ConfigReq_EnumSubscribe_value = map[string]int32{
		"NOT_SUBSCRIBE": 0,
		"SUBSCRIBE":     1,
		"UNSUBSCRIBE":   2,
		"NEED_RSP":      4,
		"NO_RSP":        8,
	}
)

func (x ConfigReq_EnumSubscribe) Enum() *ConfigReq_EnumSubscribe {
	p := new(ConfigReq_EnumSubscribe)
	*p = x
	return p
}

func (x ConfigReq_EnumSubscribe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigReq_EnumSubscribe) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (ConfigReq_EnumSubscribe) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x ConfigReq_EnumSubscribe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ConfigReq_EnumSubscribe) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ConfigReq_EnumSubscribe(num)
	return nil
}

// Deprecated: Use ConfigReq_EnumSubscribe.Descriptor instead.
func (ConfigReq_EnumSubscribe) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

//配置中心消息
type ConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameSpace  *string `protobuf:"bytes,1,opt,name=name_space,json=nameSpace" json:"name_space,omitempty"`       // 要读取的配置的命名空间
	Key        *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`                                    // 键名 空表示命名空间下的所有键
	Subscribe  *uint32 `protobuf:"varint,3,opt,name=subscribe" json:"subscribe,omitempty"`                       // 是否订阅配置的更新 见EnumSubscribe
	AppType    *uint32 `protobuf:"varint,4,opt,name=app_type,json=appType" json:"app_type,omitempty"`            // AppType
	AppId      *uint32 `protobuf:"varint,5,opt,name=app_id,json=appId" json:"app_id,omitempty"`                  // AppId
	SubAppType *uint32 `protobuf:"varint,6,opt,name=sub_app_type,json=subAppType" json:"sub_app_type,omitempty"` // AppType
	SubAppId   *uint32 `protobuf:"varint,7,opt,name=sub_app_id,json=subAppId" json:"sub_app_id,omitempty"`       // AppId
}

func (x *ConfigReq) Reset() {
	*x = ConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReq) ProtoMessage() {}

func (x *ConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReq.ProtoReflect.Descriptor instead.
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigReq) GetNameSpace() string {
	if x != nil && x.NameSpace != nil {
		return *x.NameSpace
	}
	return ""
}

func (x *ConfigReq) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ConfigReq) GetSubscribe() uint32 {
	if x != nil && x.Subscribe != nil {
		return *x.Subscribe
	}
	return 0
}

func (x *ConfigReq) GetAppType() uint32 {
	if x != nil && x.AppType != nil {
		return *x.AppType
	}
	return 0
}

func (x *ConfigReq) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *ConfigReq) GetSubAppType() uint32 {
	if x != nil && x.SubAppType != nil {
		return *x.SubAppType
	}
	return 0
}

func (x *ConfigReq) GetSubAppId() uint32 {
	if x != nil && x.SubAppId != nil {
		return *x.SubAppId
	}
	return 0
}

//配置条目
type ConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`     //
	Value *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"` //
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigItem) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

//配置响应
type ConfigRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameSpace  *string       `protobuf:"bytes,1,opt,name=name_space,json=nameSpace" json:"name_space,omitempty"`       // 要读取的配置的命名空间
	RegKey     *string       `protobuf:"bytes,2,opt,name=reg_key,json=regKey" json:"reg_key,omitempty"`                // 订阅的key
	Item       []*ConfigItem `protobuf:"bytes,3,rep,name=item" json:"item,omitempty"`                                  // 键值
	SubAppType *uint32       `protobuf:"varint,4,opt,name=sub_app_type,json=subAppType" json:"sub_app_type,omitempty"` // AppType
	SubAppId   *uint32       `protobuf:"varint,5,opt,name=sub_app_id,json=subAppId" json:"sub_app_id,omitempty"`       // AppId
}

func (x *ConfigRsp) Reset() {
	*x = ConfigRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRsp) ProtoMessage() {}

func (x *ConfigRsp) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRsp.ProtoReflect.Descriptor instead.
func (*ConfigRsp) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigRsp) GetNameSpace() string {
	if x != nil && x.NameSpace != nil {
		return *x.NameSpace
	}
	return ""
}

func (x *ConfigRsp) GetRegKey() string {
	if x != nil && x.RegKey != nil {
		return *x.RegKey
	}
	return ""
}

func (x *ConfigRsp) GetItem() []*ConfigItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ConfigRsp) GetSubAppType() uint32 {
	if x != nil && x.SubAppType != nil {
		return *x.SubAppType
	}
	return 0
}

func (x *ConfigRsp) GetSubAppId() uint32 {
	if x != nil && x.SubAppId != nil {
		return *x.SubAppId
	}
	return 0
}

//配置响应完成
type ItemRspState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameSpace  *string `protobuf:"bytes,1,opt,name=name_space,json=nameSpace" json:"name_space,omitempty"`       // 要读取的配置的命名空间
	Key        *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`                                    // 键名
	SubAppType *uint32 `protobuf:"varint,3,opt,name=sub_app_type,json=subAppType" json:"sub_app_type,omitempty"` // AppType
	SubAppId   *uint32 `protobuf:"varint,4,opt,name=sub_app_id,json=subAppId" json:"sub_app_id,omitempty"`       //
	State      *uint32 `protobuf:"varint,5,opt,name=state" json:"state,omitempty"`                               // 发送状态 0完成、1开始发送、2发送中
}

func (x *ItemRspState) Reset() {
	*x = ItemRspState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemRspState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRspState) ProtoMessage() {}

func (x *ItemRspState) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRspState.ProtoReflect.Descriptor instead.
func (*ItemRspState) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ItemRspState) GetNameSpace() string {
	if x != nil && x.NameSpace != nil {
		return *x.NameSpace
	}
	return ""
}

func (x *ItemRspState) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ItemRspState) GetSubAppType() uint32 {
	if x != nil && x.SubAppType != nil {
		return *x.SubAppType
	}
	return 0
}

func (x *ItemRspState) GetSubAppId() uint32 {
	if x != nil && x.SubAppId != nil {
		return *x.SubAppId
	}
	return 0
}

func (x *ItemRspState) GetState() uint32 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

var file_config_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x62, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xaa, 0x02, 0x0a, 0x09, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f,
	0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x75, 0x62, 0x41, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x75,
	0x62, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x73, 0x75, 0x62, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x0d, 0x45, 0x6e, 0x75, 0x6d,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54,
	0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x4e, 0x45, 0x45, 0x44, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f,
	0x5f, 0x52, 0x53, 0x50, 0x10, 0x08, 0x22, 0x34, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xae, 0x01, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61,
	0x6d, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x67,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x4b,
	0x65, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x62, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a,
	0x0c, 0x73, 0x75, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x41, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x75, 0x62, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x95, 0x01,
	0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x20, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x41, 0x70, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x75, 0x62, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x41, 0x0a, 0x09, 0x43, 0x4d, 0x44, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x44, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x44, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x73, 0x70, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x44, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67,
}

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData = file_config_proto_rawDesc
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_proto_rawDescData)
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_config_proto_goTypes = []interface{}{
	(CMDConfig)(0),               // 0: bs.config.CMDConfig
	(ConfigReq_EnumSubscribe)(0), // 1: bs.config.ConfigReq.EnumSubscribe
	(*ConfigReq)(nil),            // 2: bs.config.ConfigReq
	(*ConfigItem)(nil),           // 3: bs.config.ConfigItem
	(*ConfigRsp)(nil),            // 4: bs.config.ConfigRsp
	(*ItemRspState)(nil),         // 5: bs.config.ItemRspState
}
var file_config_proto_depIdxs = []int32{
	3, // 0: bs.config.ConfigRsp.item:type_name -> bs.config.ConfigItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemRspState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_rawDesc = nil
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
